# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: Talia-12
book_id: hexcasting:thehexbook
default_branch: main
github_repo: Hexal
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexalModPlugin
hexdoc_plugin_classname: HexalPlugin
java_lang:
    ext: java
    src: java
java_package: ram/talia/hexal
mod_display_name: Hexal
modid: hexal
multiloader: true
package_export_root: doc/src/hexdoc_hexal/_export
package_name: hexdoc-hexal
package_slug: hexdoc_hexal
package_src: doc/src/hexdoc_hexal
pages_url: https://talia-12.github.io/Hexal/
pattern_regex:
    per_world_value: 'true'
    regex: make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)
pattern_registry: common/lib/hex/HexalActions.kt
